allprojects {
    apply plugin: 'java-library'
    java {
        sourceCompatibility = 17
        targetCompatibility = 17
    }

    repositories {
        mavenCentral()
    }
}

subprojects {
    tasks.register('sourcesJar', Jar) {
        dependsOn classes
        archiveClassifier = 'sources'
        from sourceSets.main.allSource
    }

    tasks.withType(Test).configureEach {
        testLogging {
            events "skipped", "failed"
            showStandardStreams = true
            exceptionFormat = 'full'
        }
    }

    artifacts {
        archives sourcesJar
    }
}
