package com.dicio.sentences_compiler.compiler;

import com.dicio.sentences_compiler.util.CompilerError;

import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;

public interface CompilerBase {
    String autoGeneratedFileNotice = "FILE AUTO-GENERATED BY dicio-sentences-compiler. DO NOT MODIFY.";

    void addInputStream(InputStreamReader input, String inputStreamName) throws IOException, CompilerError;
    void compile(OutputStreamWriter output) throws IOException, CompilerError;
}
