package org.dicio.sentences_compiler.compiler;

import org.dicio.sentences_compiler.construct.Section;
import org.dicio.sentences_compiler.lexer.Tokenizer;
import org.dicio.sentences_compiler.parser.Parser;
import org.dicio.sentences_compiler.util.CompilerError;

import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.List;

public class CompilerToJava implements CompilerBase {
    private Tokenizer tokenizer;
    private String variablePrefix;
    private String packageName;
    private String className;

    public CompilerToJava(String variablePrefix, String packageName, String className) {
        this.tokenizer = new Tokenizer();
        this.variablePrefix = variablePrefix;
        this.packageName = packageName;
        this.className = className;
    }

    @Override
    public void addInputStream(InputStreamReader input, String inputStreamName) throws IOException, CompilerError {
        tokenizer.tokenize(input, inputStreamName);
    }

    private List<Section> getSections() throws CompilerError {
        Parser parser = new Parser(tokenizer.getTokenStream());
        return parser.parse();
    }

    public void compileToVariables(final OutputStreamWriter output) throws IOException, CompilerError {
        List<Section> sections = getSections();
        for (Section section : sections) {
            section.compileToJava(output, variablePrefix + section.getSectionId());
            output.write(";\n");
        }
        output.flush();
    }

    @Override
    public void compile(OutputStreamWriter output) throws IOException, CompilerError {
        output.write("/*\n * ");
        output.write(autoGeneratedFileNotice);
        output.write("\n */\n\n");

        output.write("package ");
        output.write(packageName);
        output.write(";\n" +
                "import org.dicio.component.InputRecognizer;\n" +
                "import org.dicio.component.standard.Sentence;\n" +
                "import org.dicio.component.standard.StandardRecognizerData;\n" +
                "import org.dicio.component.standard.Word;\n" +
                "public class ");
        output.write(className);

        output.write(" {\n");
        compileToVariables(output);
        output.write("}\n");
        output.flush();
    }
}
